---
all:
  vars:
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_user: "{{ vault_lab_user }}"
    ansible_password: "{{ vault_lab_password }}"
    ansible_become: true
    ansible_become_method: enable
    ansible_become_password: "{{ vault_enable_secret }}"

  children:
    switches:
      hosts:
        sw1:
          ansible_host: 10.255.0.11
        sw2:
          ansible_host: 10.255.0.12
        sw3:
          ansible_host: 10.0.99.3
        sw4:
          ansible_host: 10.0.99.4

    routers:
      hosts:
        r1:
          ansible_host: 10.255.0.1
        r2:
          ansible_host: 10.255.0.2
